### ISSUE TITLE
ID editor

### ISSUE THREAD

**Issue by diskmanti** [OpenLabsHackerspace/openlabs-geoportal#1]
Could be useful to add the wms service url compatible with ID editor. A lot of mappers use ID instead of JOSM to add data to OSM.

**Comment by jbelien** [comment]
Excellent idea !

Once it's ready I'll add it in default settings for iD and JOSM (I need to check the license).

I'll update the README file but here is how to do it right now :
- Got to *EDIT* mode in iD
- Open *Background Settings* (shortcut: `B`)
- Click on *Custom*
- Paste `http://149.202.183.195/mapcache/tms/1.0.0/tirana@GoogleMapsCompatible/{z}/{x}/{-y}.png`
- Click on *OK*
- Enjoy! 👍

**Comment by diskmanti** [comment]
Just checked it. It work beautifully 👍
