### ISSUE TITLE
Different layer for bus

### ISSUE THREAD

**Issue by diskmanti** [OpenLabsHackerspace/openlabs-geoportal#11]
Can a different layer be created only for bus routes, so it can be easier to use that layer on top of something else for comparison or other reasons?

**Comment by jbelien** [comment]
Yes, I thought about it ... and forgot ! 😂 

I will create 2 individual layers : 
- streets + buildings (with background)
- public transport (with **no** background)

What do you think about that solution ?

**Comment by diskmanti** [comment]
I think it is a nice simple solutions 👍

**Comment by jbelien** [comment]
Overlay with only public transport : `https://geoportal.openlabs.cc/mapcache/tms/1.0.0/public-transport@GoogleMapsCompatibleExtended/{z}/{x}/{-y}.png` 🎉
