### ISSUE TITLE
Better Styling

### ISSUE THREAD

**Issue by diskmanti** [OpenLabsHackerspace/openlabs-geoportal#2]
How can I set up a style on mapserver based on attr. I believe that it should make it easier to map only specific buildings or street of a certain kind

**Comment by jbelien** [comment]
Best way is to check the MapServer documentation !

CLASS : http://mapserver.org/mapfile/class.html
STYLE : http://mapserver.org/mapfile/style.html

But if you have suggestions, feel free to share, I will adapt the `tirana.map` file accordingly :)

**Comment by jbelien** [comment]
Styling improved and zoom level enable up to 21 !
