### ISSUE TITLE
JOSM WMS error

### ISSUE THREAD

**Issue by diskmanti** [OpenLabsHackerspace/openlabs-geoportal#3]
WMS url for josm return an error. File not found

**Comment by jbelien** [comment]
Hello @diskmanti ,

It does work ; I just checked.
Please check your configuration according to this :

![image](https://user-images.githubusercontent.com/1150563/31601476-4a3e703e-b25a-11e7-9447-9865bd37b288.png)

**Comment by jbelien** [comment]
But to avoid such problems, I'll add this layer in JOSM default imagery settings this week ! :)

**Comment by diskmanti** [comment]
Jes you are right, with the url you provided it works. But the url:

```
https://geoportal.openlabs.cc/mapcache/?FORMAT=image/png&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=tirana&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
```

return an error, that is way I opened this issue

**Comment by jbelien** [comment]
Well, indeed, in the first box ("*Enter service URL*") you need to write `https://geoportal.openlabs.cc/mapcache/` ; that's the WMS service URL !

But you can also directly copy `https://geoportal.openlabs.cc/mapcache/?FORMAT=image/png&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=tirana&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}` in the fouth box ("*Verify generated WMS url*") ; that also work :)

I'll try to clear that up in the `README.md` !

**Comment by jbelien** [comment]
I "fixed" `README.md` ! Hope it's more clear ! :)

**Comment by diskmanti** [comment]
I believe you can close this issue
